### PR TITLE
Drive Command Corrections

### PR DESCRIPTION
**Pull request by michaelvdow**
Corrected Inversion

### CODE REVIEW

**Comment by nusgart** [comment]
Seems good.  @Vjedi729 what do you think?

**Comment by titan2022robotics** [comment]
It looks good to me! I'll edit the controller stuff later for the universal controller once I've finished it so we can try a few different controls/controllers.

Edit: Oops, looks like I'm on the wrong account. This is Vishal.

**Comment by titan2022robotics** [comment]
So I should merge this?

Edit: oops - this is Nick.

**Comment by Vjedi729** [comment]
Yeah.

**Pull request merged**
